version: '3.8'
services:
  app:
    build: .
    container_name: nogachi-api
    ports:
      - 80:80
    networks:
      - net-nogachi
    depends_on:
      - nogachi
  cinema-db:
    image: mysql
    container_name: nogachi-db
    ports:
      - 3306-3306
    volumes:
      - db-nogachi:/data/db
    networks:
      - net-nogachi
networks:
  net-nogachi:
volumes:
  db-nogachi: